### PR TITLE
Mark dependencies as private so this package can be referenced

### PR DESCRIPTION
**Pull request by mthjones**

### CODE REVIEW

**Comment by omsmith** [comment]
It can be an attribute OR a nested node? Neat I guess :P

**Comment by omsmith** [comment]
nuspec looks good :+1:

**Comment by mthjones** [comment]
> It can be an attribute OR a nested node?

Yep. All boils down to a `Dictionary<string, string>` of metadata in the end.

**Comment by mthjones** [comment]
Should I be bumping the version in this PR? Seems like if we merge without bumping it'll overwrite the old packages of that version? 🤔

**Comment by omsmith** [comment]
I'll bump it after. We don't autopublish. I suppose there's a project feed buuut, unused

**Pull request merged**
