### PR TITLE
Add a dependabot configuration

### PR DESCRIPTION
**Pull request by mthjones**
Just a barebones configuration for now. Can tweak it as needed.

### CODE REVIEW

**Comment by omsmith** [comment]
Use the `.github/dependabot.yml` if we don't need any preview features?

**Comment by j3parker** [comment]
There's a UI to switch... I've kinda just been adding the old config and clicking that button haha

**Comment by j3parker** [comment]
The new format is more verbose and I have fewer things to copy and paste it from

**Comment by mthjones** [comment]
Oops, missed the big yellow box at the top here: https://dependabot.com/docs/config-file/

I'll switch it over.

**Pull request merged**
