### PR TITLE
Bless log4net.ILog.

### PR DESCRIPTION
**Pull request by saquibmian**
Will merge after #44 to bump version.

### CODE REVIEW

**Comment by j3parker** [comment]
For interfaces in this list, we'll still check their implementations when we find them right?

**Comment by saquibmian** [comment]
I can't seem to reply directly to a comment...fail. 
No, we don't check for implementations of stuff in `KnownImmutableTypes`. We only check for implementations anything that is marked `[Immutable]` (either self or an ancestor).

**Comment by j3parker** [comment]
:shipit: we should work on that

**Comment by saquibmian** [comment]
Issue for that here: https://github.com/Brightspace/D2L.CodeStyle/issues/47

**Pull request merged**
