### PR TITLE
Add Analyzer for TestContext, check two fields 'Status' and 'State' changed in NUnit3

### PR DESCRIPTION
**Pull request by LiyueWang**

### CODE REVIEW

**Comment by saquibmian** [comment]
Remind me again, is this because `Result` has been renamed?

**Comment by LiyueWang** [comment]
- TestContext.CurrentContext.Result.State  => TestContext.CurrentContext.Result.Outcome
- TestContext.CurrentContext.Result.Status  =>  TestContext.CurrentContext.Result.Outcome.Status

**Comment by saquibmian** [comment]
Awesome, thanks. Do you think we need to be concerned about this case?

```csharp
var context = TestContext.Current;
if ( context.Result.State == blah ) // ...
```

**Comment by LiyueWang** [comment]
searched  "TestContext.CurrentContext", we don't have this case in Lms.  So I would not be much concerned about this

**Pull request merged**
