### PR TITLE
Update LegacyJsonParamBinderClasses.cs

### PR DESCRIPTION
**Pull request by edwardg8**
Adding new version of courses controller to list of legacy json param binding

### CODE REVIEW

**Comment by edwardg8** [comment]
This is similar change to @davewagler-d2l , because we are exposing a new parameter in CoursesController.

**Comment by omsmith** [comment]
David's change just went in this release - I wouldn't expect a new API version yet.

Are you planning for your changes to be post-branching?

**Comment by edwardg8** [comment]
> David's change just went in this release - I wouldn't expect a new API version yet.
> 
> Are you planning for your changes to be post-branching?

This is completely a new feature request, and will be released in next train, however it does block my current development because the static code analyzer won't pass

**Comment by omsmith** [comment]
> Are you planning for your changes to be post-branching?

So yes.

Just confirming, since if your controller was going to merge today/tomorrow, it would be incorrect to increment the API version.

**Comment by omsmith** [comment]
I'll land this tomorrow.

**Comment by edwardg8** [comment]
> > Are you planning for your changes to be post-branching?
> 
> So yes.
> 
> Just confirming, since if your controller was going to merge today/tomorrow, it would be incorrect to increment the API version.

Oh yea, this will be in the next release, you are right.

**Comment by edwardg8** [comment]
> I'll land this tomorrow.

Thanks

**Comment by j3parker** [comment]
We should get this list out of the analyzer and into a data file in the LMS repo.

**Pull request closed without merging**
