### PR TITLE
target .NET Standard 1.4 from D2L.CodeStyle.Annotations

### PR DESCRIPTION
**Pull request by omsmith**
I think this is about right. Dunno if it'll package up as expected though?

### CODE REVIEW

**Comment by omsmith** [comment]
@j3parker somethingsomething need VS2017 image on appveyor

**Comment by saquibmian** [comment]
I think we need to use `dotnet`. I'mma hijack this and test.

**Comment by omsmith** [comment]
thanks :)

**Comment by saquibmian** [comment]
This generates packages with the following structure: 

```
├── analyzer
│   ├── D2L.CodeStyle.Analyzers.nuspec
│   ├── [Content_Types].xml
│   ├── _rels
│   ├── lib
│   │   └── net461
│   │       └── D2L.CodeStyle.Analyzers.dll
│   ├── package
│   │   └── services
│   │       └── metadata
│   │           └── core-properties
│   │               └── b4f26e7db2ee41aea0d7890537508688.psmdcp
│   └── tools
│       ├── install.ps1
│       └── uninstall.ps1
├── annotations
│   ├── D2L.CodeStyle.Annotations.nuspec
│   ├── [Content_Types].xml
│   ├── _rels
│   ├── lib
│   │   └── netstandard1.4
│   │       └── D2L.CodeStyle.Annotations.dll
│   └── package
│       └── services
│           └── metadata
│               └── core-properties
│                   └── 7ef5674cdb654cbfbd119c6f1c9e4da7.psmdcp
└── test-analyzer
    ├── D2L.CodeStyle.TestAnalyzers.nuspec
    ├── [Content_Types].xml
    ├── _rels
    ├── lib
    │   └── net461
    │       └── D2L.CodeStyle.TestAnalyzers.dll
    └── package
        └── services
            └── metadata
                └── core-properties
                    └── 9949c0dfe4354eedafa49253a78c3124.psmdcp
```

Annotations is a breaking change, so we might have to bump versions (`lib\netstandard1.4` vs `lib\net461`).

**Comment by saquibmian** [comment]
This is good with me. But I'd like to run a test to make sure the LMS is cool with netstandard before I approve it. @omsmith would you be able to do that? Maybe rename the package and upload it to `nuget.build.d2l` and see if your local build works.

**Comment by omsmith** [comment]
Yeah good way to go about it. Will do

**Comment by j3parker** [comment]
Any update?

**Comment by saquibmian** [comment]
@omsmith I'm gonna close this because I dont' have time to test this, and it doesn't look like you do either.

**Pull request closed without merging**
