### PR TITLE
remove Except support from [Immutable]

### PR DESCRIPTION
**Pull request by omsmith**

### CODE REVIEW

**Comment by omsmith** [comment]
Oh oops. Updated to wrong remote. Thought some stuff was weird, lol

**Comment by omsmith** [comment]
Fixed

**Review by j3parker — APPROVED** [review]
@mthjones -- we're looking to make some bigger changes to the immutability analyzer (allow for custom immutable container types and some misc fixes). Largely this is to allow it to integrate into static DI.

This feature wasn't used much and it's helpful to cut this stuff down a bit (e.g. we're making slight tweaks to how `[Immutable]` works and it would be weird with this feature).

RE: undiff, since we have so few `Unaudited` left Littlefoot has a good handle on which exist, what their role is etc., and people can't add new ones without us knowing... so in terms of making shipping safer I think this has mostly outlived its utility.

**Review by mthjones — APPROVED** [review]
Thanks for the context. Agreed that it's outlived its usefulness, and this much red to remove whats a pretty small feature seems like a good choice to me. :shipit:

**Pull request merged**
